### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [stpettersens/cpal#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by stpettersens** [comment]
No, I will move to serde_json. Thank you for the heads up.

**Comment by stpettersens** [comment]
No, I will move to serde_json. Thank you for the heads up.
